runtime: python
env: flex
entrypoint: gunicorn -b :$PORT application:application

runtime_config:
        python_version: 3.7

# These settings are not appropriate for
# production use. We are using these to
# reduce cost during testing. For more
# info see:
# https://cloud.google.com/appengine/docs/flexible/python/configureing-your-app-with-app-yaml
manual_scaling:
        instances: 1
resources:
        cpu: 1
        memory_gb: 3
        disk_size_gb: 20
